Program cosmosolver

  ! LOAD MODULES AND LIBRARIES

  ! START TIMING PERFORMANCE OF THE CODE
  
  ! DEFINE VARIABLES, PARAMETERS, ETC.

  ! SUBROUTINE CHECKING CONSISTENCY OF INPUT VALUES

  ! SUBROUTINE CHECKING MEMORY RESOURCES

  ! SUBROUTINE SOLVING BACKGROUND EQUATIONS

  ! SUBROUTINE SOLVING PERTURBATION EQUATIONS

  ! SUBROUTINE PLOTTING OUTPUT

  ! END TIMING PERFORMANCE OF THE CODE
  
End Program cosmosolver
